"""add created_at

Revision ID: 11ad935cd0c8
Revises: 927efaac8b88
Create Date: 2025-08-28 10:27:40.917289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11ad935cd0c8'
down_revision = '927efaac8b88'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
