"""Add location_details table

Revision ID: 18925aacad67
Revises: e742409a73c6
Create Date: 2025-09-30 10:35:41.680217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18925aacad67'
down_revision = 'e742409a73c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.String(length=10), nullable=False),
    sa.Column('object_name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_details_city_id'), 'location_details', ['city_id'], unique=False)
    op.create_index(op.f('ix_location_details_id'), 'location_details', ['id'], unique=False)
    op.create_index(op.f('ix_location_details_location_id'), 'location_details', ['location_id'], unique=True)
    op.create_index(op.f('ix_location_details_object_name'), 'location_details', ['object_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_location_details_object_name'), table_name='location_details')
    op.drop_index(op.f('ix_location_details_location_id'), table_name='location_details')
    op.drop_index(op.f('ix_location_details_id'), table_name='location_details')
    op.drop_index(op.f('ix_location_details_city_id'), table_name='location_details')
    op.drop_table('location_details')
    # ### end Alembic commands ###
