"""switched category and title places

Revision ID: 2b85d11826f9
Revises: 70fd21656534
Create Date: 2025-09-07 12:03:25.750450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b85d11826f9'
down_revision = '70fd21656534'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
