"""add created_at to locations

Revision ID: 45b04c3eaef9
Revises: 11ad935cd0c8
Create Date: 2025-08-28 10:28:59.884977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45b04c3eaef9'
down_revision = '11ad935cd0c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
