"""create locations table

Revision ID: 7c6422985db0
Revises: 45b04c3eaef9
Create Date: 2025-08-28 10:33:01.211820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c6422985db0'
down_revision = '45b04c3eaef9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
