"""add cities table and city_id to locations

Revision ID: 93516b0a169b
Revises: 74884d632b75
Create Date: 2025-09-09 09:24:12.702529

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '93516b0a169b'
down_revision = '74884d632b75'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_locations_category'), table_name='locations')
    op.drop_index(op.f('ix_locations_category_title'), table_name='locations')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_latitude'), table_name='locations')
    op.drop_index(op.f('ix_locations_longitude'), table_name='locations')
    op.drop_index(op.f('ix_locations_title'), table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category', sa.VARCHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('locations_pkey'))
    )
    op.create_index(op.f('ix_locations_title'), 'locations', ['title'], unique=False)
    op.create_index(op.f('ix_locations_longitude'), 'locations', ['longitude'], unique=False)
    op.create_index(op.f('ix_locations_latitude'), 'locations', ['latitude'], unique=False)
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_index(op.f('ix_locations_category_title'), 'locations', ['category', 'title'], unique=False)
    op.create_index(op.f('ix_locations_category'), 'locations', ['category'], unique=False)
    # ### end Alembic commands ###
